name: AlphaLadders
author: Strahan
main: com.sylvcraft.AlphaLadders
version: 1.0
description: Allows you to use spaced ladders like you could in alpha
commands:
  alad:
    description: Plugin command
